### ISSUE TITLE
"Disconnected from the server" error when looking up actor/director.

### ISSUE THREAD

**Issue by biskwikman** [TMBish/Stratton#1]
Eeeeey I get this error when I look up someone whose name doesn't pop up in the list of autocomplete suggestions. I don't know if that is intentional or not but it means I can't lookup John Travolta.

**Comment by TMBish** [comment]
Hey @biskwikman !

That's a good bug you've found there. Non auto-completed search works on my personal machine but not on the server so I'll have a look at it.

In the meantime there's 2 workarounds:
1. Type your non auto-completed searches in title case: eg. "John Travolta" (Fukn stupid I know)
2. Travolta is actually in the drop-down list, just type "John" and scroll down. The search should work if you select him that way.
__NB:__ "John T" filters out Travolta for some weird reason, I think it might be an encoding issue somewhere.

These are the kind of infuriatingly minor and nonsensical programming issues that make me aware of why I could literally never be a software developer making actual applications for the world.

Cheers mate
